/* eslint-disable @next/next/no-sync-scripts */
"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import { usePathname } from "next/navigation";


const inter = Inter({ subsets: ["latin"] });
const disableNavbar = ["/login", "/register"];

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  return (
    <html lang="en">
    <head>
      <title>Zakola Next</title>
      <meta name="description" content="Zona Akses Kependidikan dan Kelola Akademik"/>
     </head>
      <body className={inter.className}>
        {!disableNavbar.includes(pathname) && <Navbar />}
        {children}
      </body>
    </html>
  );
}
